import type { MultiTierPackage } from "../_lib/types";
import { vitaminTiers, feverTiers, cardiacTiers, menopauseTiers, bloatingTiers, fitnessTiers } from "./tier-data";

export const multiTierPackages: Record<number, MultiTierPackage> = {
  2: {
    name: "Advanced Smart Check Profile",
    tiers: [
      {
        key: "female",
        name: "Female",
        price: "4,750",
        tests: [
          "CBC with ESR",
          "Blood Glucose Fasting*",
          "Lipid Profile*",
          "Kidney Function Test",
          "Liver Function Test",
          "Magnesium",
          "CPK",
          "Thyroid Profile with FT3, FT4, Ultra-sensitive TSH",
          "HbA1c (Glycosylated Hemoglobin)",
        ],
      },
      {
        key: "male",
        name: "Male with PSA (Total)",
        price: "5,150",
        tests: [
          "CBC with ESR",
          "Blood Glucose Fasting*",
          "Lipid Profile*",
          "Kidney Function Test",
          "Liver Function Test",
          "Magnesium",
          "CPK",
          "Thyroid Profile with FT3, FT4, Ultra-sensitive TSH",
          "HbA1c (Glycosylated Hemoglobin)",
          "PSA-Total",
        ],
      },
    ],
  },
  3: {
    name: "Superior Smart Check Profile",
    tiers: [
      {
        key: "female",
        name: "Female",
        price: "8,600",
        tests: [
          "CBC with ESR",
          "Blood Glucose Fasting*",
          "Lipid Profile*",
          "Kidney Function Test",
          "Liver Function Test",
          "Magnesium",
          "CPK",
          "Thyroid Profile with FT3, FT4, Ultra-sensitive TSH",
          "HbA1c (Glycosylated Hemoglobin)",
          "Vitamin D3",
          "Vitamin B12",
          "IgE-Total",
        ],
      },
      {
        key: "male",
        name: "Male with PSA (Total)",
        price: "9,000",
        tests: [
          "CBC with ESR",
          "Blood Glucose Fasting*",
          "Lipid Profile*",
          "Kidney Function Test",
          "Liver Function Test",
          "Magnesium",
          "CPK",
          "Thyroid Profile with FT3, FT4, Ultra-sensitive TSH",
          "HbA1c (Glycosylated Hemoglobin)",
          "Vitamin D3",
          "Vitamin B12",
          "IgE-Total",
          "PSA-Total",
        ],
      },
    ],
  },
  4: {
    name: "Premium Smart Check Profile",
    tiers: [
      {
        key: "female",
        name: "Female",
        price: "11,500",
        tests: [
          "CBC with ESR",
          "Blood Glucose Fasting*",
          "Lipid Profile*",
          "Kidney Function Test",
          "Liver Function Test",
          "Magnesium",
          "CPK",
          "Thyroid Profile with FT3, FT4, Ultra-sensitive TSH",
          "HbA1c (Glycosylated Hemoglobin)",
          "IgE-Total",
          "Vitamin D3",
          "Vitamin B12",
          "Vitamin B9/Folic Acid",
          "hs-CRP",
          "Iron",
          "Ferritin",
          "U.I.B.C.",
          "T.I.B.C.",
          "Transferrin Saturation",
          "Comprehensive Urine Examination",
        ],
      },
      {
        key: "male",
        name: "Male with PSA (Total)",
        price: "11,900",
        tests: [
          "CBC with ESR",
          "Blood Glucose Fasting*",
          "Lipid Profile*",
          "Kidney Function Test",
          "Liver Function Test",
          "Magnesium",
          "CPK",
          "Thyroid Profile with FT3, FT4, Ultra-sensitive TSH",
          "HbA1c (Glycosylated Hemoglobin)",
          "IgE-Total",
          "Vitamin D3",
          "Vitamin B12",
          "Vitamin B9/Folic Acid",
          "hs-CRP",
          "Iron",
          "Ferritin",
          "U.I.B.C.",
          "T.I.B.C.",
          "Transferrin Saturation",
          "Comprehensive Urine Examination",
          "PSA-Total",
        ],
      },
    ],
  },
  7: {
    name: "Vitamins and Minerals Profile",
    tiers: [
      { key: "basic", name: "Basic", price: vitaminTiers.basic.price, tests: vitaminTiers.basic.tests },
      { key: "advanced", name: "Advanced", price: vitaminTiers.advanced.price, tests: vitaminTiers.advanced.tests },
      { key: "comprehensive", name: "Comprehensive", price: vitaminTiers.comprehensive.price, tests: vitaminTiers.comprehensive.tests },
    ],
  },
  12: {
    name: "Fever Profile",
    tiers: [
      { key: "monsoon", name: "Monsoon", price: feverTiers.monsoon.price, tests: feverTiers.monsoon.tests },
      { key: "basic", name: "Basic", price: feverTiers.basic.price, tests: feverTiers.basic.tests },
      { key: "advanced", name: "Advanced", price: feverTiers.advanced.price, tests: feverTiers.advanced.tests },
    ],
  },
  17: {
    name: "Cardiac Risk Profile",
    tiers: cardiacTiers.map((tier) => ({
      key: tier.name.toLowerCase().replace(/\s+/g, "_"),
      name: tier.name,
      price: tier.price,
      tests: tier.tests,
    })),
  },
  23: {
    name: "Menopause Profile",
    tiers: menopauseTiers.map((tier) => ({
      key: tier.name.toLowerCase(),
      name: tier.name,
      price: tier.price,
      tests: Object.keys(tier.tests).filter((test) => tier.tests[test]),
    })),
  },
  24: {
    name: "Bloating Profile",
    tiers: bloatingTiers.map((tier) => ({
      key: tier.name.toLowerCase().replace(/\s+/g, "_"),
      name: tier.name,
      price: tier.price,
      tests: Object.keys(tier.tests).filter((test) => tier.tests[test]),
    })),
  },
  31: {
    name: "Fitness Profile",
    tiers: [
      { key: "female", name: "Female", price: fitnessTiers.female.price, tests: fitnessTiers.female.tests },
      { key: "male", name: "Male", price: fitnessTiers.male.price, tests: fitnessTiers.male.tests },
    ],
  },
};
