import type { TestProfile } from "../_lib/types";

export const profiles: TestProfile[] = [
  {
    id: 1,
    package_name: "Smart Check Profile",
    category: "Basic Health",
    package_detail:
      "This is a basic yet powerful package which gives a bird's eye view of your inner metabolism. It has Complete Blood Count which in itself provides a wealth of information regarding anemia (Hemoglobin), infections (TLC, DLC), blood cancers; lipids; blood sugar evaluation; kidney and liver evaluation; Magnesium - a key mineral, deficiency of which causes fatigue and a muscle marker CPK",
    package_rate: "3,500",
    tests_details: [
      "CBC with ESR",
      "Blood Glucose Fasting*",
      "Lipid Profile*",
      "Kidney Function Test",
      "Liver Function Test",
      "Magnesium",
      "CPK",
    ],
    notes_contents: [
      "Tests marked with * require minimum 10-12 hours fasting.",
    ],
  },
  {
    id: 2,
    package_name: "Advanced Smart Check Profile",
    category: "Advanced Health",
    package_detail:
      "This package couples the advantage of Glycosylated Hemoglobin (HbA1C) which gives you an average estimation of your sugar levels over the past 3 months, as well as the well-established Thyroid Profile with Free T3, Free T4 and Ultra-sensitive TSH while continuing to give you all the benefits of a Smart Check Profile.",
    package_rate: "4,750",
    male_price: "5,150",
    tests_details: [
      "CBC with ESR",
      "Blood Glucose Fasting*",
      "Lipid Profile*",
      "Kidney Function Test",
      "Liver Function Test",
      "Magnesium",
      "CPK",
      "Thyroid Profile with FT3, FT4, Ultra-sensitive TSH",
      "HbA1c (Glycosylated Hemoglobin)",
    ],
    notes_contents: [
      "Tests marked with * require minimum 10-12 hours fasting.",
      "PSA (Total) is available for males at an additional cost.",
    ],
  },
  {
    id: 3,
    package_name: "Superior Smart Check Profile",
    category: "Advanced Health",
    package_detail:
      "The superior smart check profile adds an assessment of key vitamins such as vitamin D3 and vitamin B12 along with IgE (which gives you an indication of your body's response to allergy), beyond all the value of an Advanced Smart Check. This package encourages you to consider a superior choice in a health check & this package is highly recommended for persons of any age group who are looking for a simplified yet effective evaluation by blood tests.",
    package_rate: "8,600",
    male_price: "9,000",
    tests_details: [
      "CBC with ESR",
      "Blood Glucose Fasting*",
      "Lipid Profile*",
      "Kidney Function Test",
      "Liver Function Test",
      "Magnesium",
      "CPK",
      "Thyroid Profile with FT3, FT4, Ultra-sensitive TSH",
      "HbA1c (Glycosylated Hemoglobin)",
      "IgE-Total",
      "Vitamin D3",
      "Vitamin B12",
    ],
    notes_contents: [
      "Tests marked with * require minimum 10-12 hours fasting.",
      "PSA (Total) is available for males at an additional cost.",
    ],
  },
  {
    id: 4,
    package_name: "Premium Smart Check Profile",
    category: "Premium Health",
    package_detail:
      "Premium smart check profile amplifies the advantages of the superior smart check by including additional tests that provide a greater in-depth analysis of your health. The additional tests include Vitamin B9/ folic acid, a detailed urine analysis, complete iron studies including ferritin, iron binding capacity, and transferrin saturation. The inclusion of High Sensitive CRP is a huge plus with the test being a sensitive marker for evidence of inflammation as well as cardiac risk assessment. This package is highly recommended to persons of any age group who are looking for an extensive and effective evaluation by blood tests.",
    package_rate: "11,500",
    male_price: "11,900",
    tests_details: [
      "CBC with ESR",
      "Blood Glucose Fasting*",
      "Lipid Profile*",
      "Kidney Function Test",
      "Liver Function Test",
      "Magnesium",
      "CPK",
      "Thyroid Profile with FT3, FT4, Ultra-sensitive TSH",
      "HbA1c (Glycosylated Hemoglobin)",
      "IgE-Total",
      "Vitamin D3",
      "Vitamin B12",
      "Vitamin B9/Folic Acid",
      "hs-CRP",
      "Iron",
      "Ferritin",
      "U.I.B.C.",
      "T.I.B.C.",
      "Transferrin Saturation",
      "Comprehensive Urine Examination",
    ],
    notes_contents: [
      "Tests marked with * require minimum 10-12 hours fasting.",
      "PSA (Total) is available for males at an additional cost.",
    ],
  },
  {
    id: 5,
    package_name: "Comprehensive Health Profile (CHP)",
    category: "Comprehensive",
    package_detail:
      "An all inclusive package covering various tests scientifically proven to have a role in preventive health testing. This package is also extremely useful for the monitoring of patients with Hypertension, Diabetes, Cardiac, Kidney, Thyroid, Pancreas and Liver conditions; Vitamin deficiencies and Inflammation. CHP also has Cystatin C & Microalbuminuria, an early indicator of kidney disease; High Sensitivity CRP, a very sensitive marker of Inflammation/cardiac risk; total serum IgE as well as a detailed urine examination. This package is highly recommended to persons of any age group who are looking for comprehensive insights into their health via urine and blood tests.",
    package_rate: "15,000",
    tests_details: [
      "CBC with ESR",
      "Blood Glucose Fasting*",
      "Blood Glucose PP**",
      "Lipid Profile*",
      "Kidney Function Test",
      "Cystatin C",
      "Liver Function Test",
      "Magnesium",
      "CPK",
      "Lipoprotein [a]",
      "Homocysteine",
      "Apolipoprotein A",
      "Apolipoprotein B",
      "Vitamins & Minerals Profile (Vitamin D3, Vitamin B12, Vitamin B9/Folic Acid, Iron, Ferritin, U.I.B.C., T.I.B.C., Transferrin Saturation, Zinc)",
      "Thyroid Profile with FT3, FT4, Ultra-sensitive TSH",
      "HbA1c (Glycosylated Hemoglobin)",
      "IgE-Total",
      "hs-CRP",
      "Microalbuminuria",
      "Amylase",
      "Lipase",
      "Comprehensive Urine Examination",
    ],
    notes_contents: [
      "Tests marked with * require minimum 10-12 hours fasting.",
      "Tests marked with ** are to be performed as PP (post prandial i.e. 2 hours after finishing your meal).",
    ],
  },
  {
    id: 6,
    package_name: "Comprehensive Health Profile with PSA",
    category: "Comprehensive",
    package_detail:
      "An all inclusive package covering various tests scientifically proven to have a role in preventive health testing. This package is also extremely useful for the monitoring of patients with Hypertension, Diabetes, Cardiac, Kidney, Thyroid, Pancreas and Liver conditions; Vitamin deficiencies and Inflammation. CHP also has Cystatin C & Microalbuminuria, an early indicator of kidney disease; High Sensitivity CRP, a very sensitive marker of Inflammation/cardiac risk; total serum IgE as well as a detailed urine examination. Prostate Specific Antigen (Total PSA, Free PSA along with the ratio), an established marker to screen for prostate cancers also forms a part of this package.",
    package_rate: "16,500",
    tests_details: [
      "CBC with ESR",
      "Blood Glucose Fasting*",
      "Blood Glucose PP**",
      "Lipid Profile*",
      "Kidney Function Test",
      "Cystatin C",
      "Liver Function Test",
      "Magnesium",
      "CPK",
      "Lipoprotein [a]",
      "Homocysteine",
      "Apolipoprotein A",
      "Apolipoprotein B",
      "Vitamins & Minerals Profile (Vitamin D3, Vitamin B12, Vitamin B9/Folic Acid, Iron, Ferritin, U.I.B.C., T.I.B.C., Transferrin Saturation, Zinc)",
      "Thyroid Profile with FT3, FT4, Ultra-sensitive TSH",
      "HbA1c (Glycosylated Hemoglobin)",
      "Comprehensive Urine Examination",
      "IgE-Total",
      "hs-CRP",
      "Microalbuminuria",
      "Amylase",
      "Lipase",
      "PSA-Total",
      "PSA Free",
    ],
    notes_contents: [
      "Tests marked with * require minimum 10-12 hours fasting.",
      "Tests marked with ** are to be performed as PP (post prandial i.e. 2 hours after finishing your meal).",
    ],
  },
  {
    id: 7,
    package_name: "Vitamins and Minerals Profile",
    category: "Specialized",
    package_detail:
      "Deficiency of vitamins and minerals is a common cause of anemia, fatigue, muscle cramps, joint pains, tingling sensations, frequent infections, and other vague health complaints. These micronutrients are vital for immunity and overall well-being. Adequate Vitamin D protects against infections and reduces the risk of several non-communicable diseases. This comprehensive profile is an excellent add-on to Smart Check, Advanced Smart Check, or any monitoring panel. Beyond the basics, it includes Vitamin A for vision, Vitamin E for skin and immune health, Vitamin C for healing and antioxidant defense, RBC folate (a more accurate estimate of vitamin B9), and STFR\u2014an advanced marker to detect iron deficiency and guide iron therapy. Also included is a urine test to check whether your body has the iodine it needs for peak energy and metabolism.\n\nAdditionally, it is advisable to monitor these values if you have been taking vitamins for a prolonged period without any doctor's advice or prescription.",
    package_rate: "6,500",
    tests_details: [
      "Vitamin D3",
      "Vitamin B12",
      "Total Calcium",
      "Phosphorus",
      "Folic Acid (Vitamin B9)",
      "Iron",
      "Ferritin",
      "T.I.B.C.",
      "U.I.B.C.",
      "Magnesium",
      "Zinc",
      "Transferrin Saturation",
      "Vitamin A*",
      "Vitamin E*",
      "Urinary Iodine*",
      "STFR (Soluble Transferrin Receptor)",
      "RBC Folate",
      "Ionized Calcium",
      "Vitamin C*",
    ],
    notes_contents: [
      "Tests marked with * require minimum 10-12 hours fasting.",
    ],
  },
  {
    id: 8,
    package_name: "Female Hormone Profile",
    category: "Hormonal",
    package_detail:
      "An imbalance in female hormones can lead to irregular periods, bloating, fatigue, irritability, hair loss, palpitations, mood swings, diabetes, lack of ability to concentrate, issues with fertility, hirsutism(excessive hair), premature menarche, etc. This Profile can also be used in various conditions such as amenorrhea, dysfunctional uterine bleeding & to assess ovarian function. Physicians often ask for a Female Hormonal Profile to be performed on Day 2/3 of the menstrual cycle with a pooled and mid morning sample for prolactin.",
    package_rate: "7,500",
    tests_details: [
      "FSH",
      "LH",
      "Prolactin (Pooled)",
      "Estrogen",
      "Progesterone",
      "AMH",
      "Thyroid Profile with FT3, FT4, Ultra-sensitive TSH",
      "DHEAS (Sulphate)",
    ],
    notes_contents: [],
  },
  {
    id: 9,
    package_name: "PCOD Profile",
    category: "Specialized",
    package_detail:
      "Poly Cystic Ovary Disease (PCOD) is a commonly encountered condition associated with hormonal imbalance, ovarian cysts &/or irregular periods. The PCOD profile gives you an option of testing hormone levels along with conditions like diabetes and thyroid dysfunction that may be commonly associated with PCOD. These test results along with imaging techniques & a physician's guidance are required to reach a conclusive diagnosis.",
    package_rate: "9,000",
    tests_details: [
      "FSH",
      "LH",
      "Progesterone",
      "Insulin (Fasting)*",
      "Blood Glucose Fasting*",
      "HOMA-IR* (Insulin Resistance Index)",
      "Estradiol (E2)",
      "Thyroid Profile with FT3, FT4, Ultra-sensitive TSH",
      "Testosterone Total",
      "Testosterone Free",
      "Prolactin (Pooled)",
      "DHEAS (Sulphate)",
    ],
    notes_contents: [
      "Tests marked with * require minimum 10-12 hours fasting.",
    ],
  },
  {
    id: 10,
    package_name: "Comprehensive Thyroid Profile",
    category: "Specialized",
    package_detail:
      "Dr. Dangs Lab offers a state-of-the-art Comprehensive Thyroid Profile, a vital tool in assessing thyroid health. This comprehensive panel includes key markers such as Thyroid profile with FT3, FT4, ultra-sensitive TSH, anti-thyroglobulin antibodies, anti-thyroid peroxidase (Anti-TPO), reverse T3 (RT3), as well as Total T3 and Total T4 levels. These precise measurements provide a thorough evaluation of thyroid function, aiding in the diagnosis and management of thyroid disorders, ensuring comprehensive and accurate insights into the individual's health.",
    package_rate: "9,800",
    tests_details: [
      "Thyroid Profile with FT3, FT4, Ultra-sensitive TSH",
      "T3, Total",
      "T4, Total",
      "Anti-TG (Anti-thyroglobulin antibodies)",
      "Anti-TPO (Anti-thyroid peroxidase antibodies)",
      "Reverse T3 (RT3)",
    ],
    notes_contents: [],
  },
  {
    id: 11,
    package_name: "Arthritis Profile",
    category: "Specialized",
    package_detail:
      "The Arthritis Profile assesses the several reasons due to which an individual could be having pain in the bones or joints. This profile confirms the Rheumatoid Arthritis factor (RA), and also has a vitamin check, markers for inflammation and autoimmune screening (ANA). These assist the clinician in making a definite diagnosis. The detection of anti-CCP antibodies confirms the presence of rheumatoid arthritis, establishes a prognosis for the progression of the disease and helps determine the best possible treatment.",
    package_rate: "7,500",
    tests_details: [
      "CBC with ESR",
      "CRP",
      "RA Factor",
      "ANA",
      "Uric Acid",
      "ASO (Antistreptolysin O)",
      "Anti-CCP",
      "Total Calcium",
      "Ionized Calcium",
      "Phosphorus",
      "Vitamin D3",
    ],
    notes_contents: [],
  },
  {
    id: 12,
    package_name: "Fever Profiles",
    category: "Specialized",
    package_detail:
      "Fever Profile Basic screens for common causes of fever such as Malaria, Typhoid, Dengue, and Urinary infections. It also includes CBC with ESR, the most frequently prescribed test, providing valuable information on blood counts including platelets to help define the nature of fever and its treatment. Fever Profile Advanced offers all these benefits, along with extended investigations for Typhoid, Chikungunya, Scrub Typhus, Mumps, Leptospira, and Lyme's disease. It also includes culture/sensitivity of urine, throat, and blood samples, CRP to assess inflammation and recovery, and liver enzymes as markers of liver infection. For seasonal needs, our Monsoon Fever Panel provides a focused approach to quickly identify the most common infections prevalent during the rainy season.",
    package_rate: "4,900",
    tests_details: [
      "Malaria Parasite",
      "Malaria Ag",
      "CBC",
      "S.G.O.T",
      "S.G.P.T",
      "Widal",
      "CRP",
      "Dengue NS1",
      "Dengue IgM",
      "Dengue IgG",
      "Comprehensive Urine Examination",
      "Typhidot IgM",
      "Throat Swab Culture",
      "Blood Culture",
      "Urine Culture",
      "Chikungunya PCR",
      "Scrub Typhus PCR",
      "Leptospira IgM",
      "Lyme's IgM",
      "Mumps IgM",
    ],
    notes_contents: [],
  },
  {
    id: 13,
    package_name: "Flu Panels",
    category: "Specialized",
    package_detail:
      "Respiratory infections can be caused not only by influenza viruses but also by a host of other pathogens. These commonly spread through respiratory droplets, and symptoms may include fever, congestion, cough, sore throat, fatigue, and body aches, etc. Diagnosing accurately is essential to manage symptoms early, reduce complications, and prevent unnecessary use of antibiotics. Dr. Dangs Lab offers advanced diagnostic options for upper respiratory infections through our Influenza Panel, Comprehensive Flu Panel, and Respiratory BioFire. These tests vary in coverage, identifying a wide range of pathogens, including influenza viruses and other respiratory agents. Using oropharyngeal and nasopharyngeal swabs, these tests provide precise results, helping physicians tailor treatment accordingly. Accurate testing ensures better patient care and supports public health by managing seasonal outbreaks effectively.",
    tests_details: ["Please refer to the detailed panel."],
    link: "https://testprofiles.drdangslab.com/static/files/Updated-Flu-Panels-1.4.23.pdf",
    notes_contents: [],
  },
  {
    id: 14,
    package_name: "Basic Male Hormonal Profile",
    category: "Hormonal",
    package_detail:
      "Basic male hormonal profile measures the levels of hormones that play an active role in men's health and may be an important part of sexual health as well as general wellbeing in men. Cortisol, also known as the stress hormone, and a Thyroid profile with FT3, FT4 & Ultra-sensitive TSH are included along with all other essential male hormones. This profile gives a broader picture of your health and is useful in determining the reasons behind general weakness, inability to lose weight, sexual dysfunctions, and various lifestyle-related issues among males.",
    package_rate: "10,000",
    tests_details: [
      "FSH",
      "LH",
      "Cortisol",
      "DHEAS (Sulphate)",
      "Estrogen (E2)",
      "Free Androgen Index",
      "SHBG",
      "Thyroid Profile with FT3, FT4, Ultra-sensitive TSH",
      "Testosterone Total",
      "Testosterone Free",
      "Prolactin (Pooled)",
    ],
    notes_contents: [],
  },
  {
    id: 15,
    package_name: "Basic STD Profile",
    category: "Specialized",
    package_detail:
      "The basic sexually transmitted disease profile is a combination of the most frequently contracted and screened for infections linked to unprotected sex. The reason to get an STD panel done is to identify and treat early any infection and also prevent passing on the infection to partner. HIV Combo comprising of the HIV P24 Antigen & the HIV Antibody, Hepatitis B, C, Syphilis & genital Herpes diagnosis can be made by the tests included in the panel.",
    package_rate: "4,000",
    tests_details: [
      "HIV Combo",
      "HBsAg for Hepatitis B",
      "HCV Antibodies for Hepatitis C",
      "Syphilis by CMIA",
      "Herpes Simplex 2 IgM",
    ],
    notes_contents: [],
  },
  {
    id: 16,
    package_name: "Comprehensive STD Profile",
    category: "Specialized",
    package_detail:
      "Comprehensive STD profile additionally tests for the molecular STD panel (Chlamydia trachomatis, Neisseria gonorrhoeae, Trichomonas vaginalis, Gardnerella vaginalis, Mycoplasma genitalium, Mycoplasma hominis, Herpes simplex virus 1/2, Ureaplasma species, Candida albicans, Cytomegalovirus, Human papillomavirus types 16 & 18) beyond testing for HIV, Hepatitis B, Hepatitis C and Syphilis which forms part of the basic STD profile. Organisms included in the comprehensive STD panel include common sexually transmitted infections often presenting as unusual discharge, genital sores, itching, pain during urination or sex. The molecular STD panel tests are tested using a molecular method, i.e., nucleic acid amplification technique (NAAT), which provides the very best of results. Many STDs can also be asymptomatic, so regular screening is important, especially if you have new or multiple partners. Always keep in mind that the period of time when while testing for STDs.",
    package_rate: "13,800",
    tests_details: [
      "HIV Combo",
      "HBsAg for Hepatitis B",
      "HCV Antibodies for Hepatitis C",
      "Herpes Simplex 2 IgM",
      "Syphilis by CMIA",
      "TPHA (Treponema Pallidum Hemagglutination Assay)",
      "RPR (Rapid Plasma Reagin)",
      "Chlamydia Trachomatis",
      "Neisseria Gonorrhoeae",
      "Trichomonas Vaginalis",
      "Gardnerella vaginalis",
      "Mycoplasma genitalium",
      "Mycoplasma hominis",
      "Herpes simplex virus 1/2 (PCR)",
      "Ureaplasma species",
      "Candida albicans",
      "Cytomegalovirus",
      "Human Papillomavirus types 16",
      "Human Papillomavirus types 18",
    ],
    notes_contents: [],
  },
  {
    id: 17,
    package_name: "Allerginius Dx Test",
    category: "Specialized",
    package_detail:
      "The Allerginius Dx Test is a comprehensive diagnostic panel designed to identify specific allergens causing allergic reactions. It helps in detecting sensitivities to common environmental allergens such as pollen, dust mites, mold, pet dander, and certain food items. This test aids physicians in determining the root cause of allergic symptoms like sneezing, runny nose, skin rashes, itching, and respiratory difficulties, allowing for personalized treatment and preventive strategies.",
    tests_details: ["Please refer to details Allerginius Dx panel."],
    notes_contents: [],
    link: "https://testprofiles.drdangslab.com/static/files/ALLERGYNIUS%20DX%20-%20ALLERGY%20(%20IGE%20BASED%20).pdf",
  },
  {
    id: 18,
    package_name: "Food Intolerance Profiles (IgG Based)",
    category: "Specialized",
    package_detail:
      "IgG-based food intolerance (IMUPRO) is exclusively due to your diet and most commonly presents with gut-related symptoms such as bloating, gastritis, constipation, diarrhoea, irritable bowel syndrome (IBS), inflammatory bowel disease (IBD), nausea, and also other symptoms like chronic pain, chronic weight problems, skin problems (atopic dermatitis, eczema, psoriasis), and nervous system disorders. There are various food panels available for testing: 22/44/90 vegetarian, 90 non-vegetarian, 180, and 270 foods are available, and the one most appropriate for you needs to be selected as per your daily diet.",
    tests_details: ["Please refer to the detailed panel."],
    notes_contents: [],
    link: "https://testprofiles.drdangslab.com/static/files/Imupro%20brochure%20(April%202025).pdf",
  },
  {
    id: 19,
    package_name: "Cardiac Risk Profiles",
    category: "Specialized",
    package_detail:
      "Dr. Dangs Lab's cardiac risk profiles consist of a group of advanced tests that provide immediate, actionable clinical information for the risk stratification and aid in predicting future cardiac events. These comprehensive panels include high-sensitivity markers like hs-CRP, homocysteine, cardiac troponins, and advanced lipid testing to assess cardiovascular risk factors. Early detection through these profiles enables timely intervention and better management of heart health.",
    tests_details: [
      "Please refer to the detailed cardiac risk profile options.",
    ],
    notes_contents: [
      {
        label: "Note",
        note: "Tests marked with * require minimum 10-12 hours fasting.",
      },
    ],
    link: "https://testprofiles.drdangslab.com/static/files/Comprehensive%20Cardiac%20Risk%20Profile%20with%20Lp-PLA.pdf",
  },
  {
    id: 20,
    package_name: "Basic Obesity Profile",
    category: "Specialized",
    package_detail:
      "This profile is helpful for individuals who are planning weight reduction for themselves and need to assess metabolic functions at functional levels that might contribute to obesity. This profile assesses the common causes of obesity, including derangements in lipid levels, insulin resistance, thyroid, and a liver function test, along with the stress hormone, i.e., cortisol. Leptin, a hormone that plays an integral role in regulating hunger, appetite, and body weight, is also included in this basic obesity profile.",
    package_rate: "11,500",
    tests_details: [
      "CBC",
      "Blood Glucose Fasting*",
      "Insulin Fasting*",
      "Liver Function Test",
      "Thyroid Profile with FT3, FT4, Ultra-sensitive TSH",
      "Lipid Profile*",
      "Cortisol (Morning)",
      "Testosterone Total",
      "Blood Glucose PP**",
      "Insulin PP**",
      "HOMA-IR* (Insulin Resistance Index)",
      "HbA1c (Glycosylated Hemoglobin)",
      "CRP",
      "Leptin",
    ],
    notes_contents: [
      "Tests marked with * require minimum 10-12 hours fasting.",
      "Tests marked ** are to be performed as PP (post prandial i.e. 2 hours after finishing your meal).",
      "For details of Advanced Obesity Profile & METACHECK [Metacheck analyses 86/7 food items to provide personalised diet recommendations as per the individual's genetic makeup to help you lose weight & reach your fitness goals] kindly contact 999-999-2020 or our frontdesk.",
    ],
  },
  {
    id: 21,
    package_name: "Diabetes/Hypertension Profile",
    category: "Specialized",
    package_detail:
      "Diabetes is understood as a disease where there is excess glucose in the blood, and it is hence often assumed that having fewer sweets can help overcome the illness. However, it is critical to keep a lookout for the complications of diabetes, which cause permanent damage. A fair number of patients have both hypertension as well as diabetes, which doubles the risk of organ damage. This profile puts together tests to monitor diabetes and hypertension and their commonly associated complications.",
    package_rate: "4,500",
    tests_details: [
      "Blood Glucose Fasting*",
      "Blood Glucose PP**",
      "HbA1c (Glycosylated Hemoglobin)",
      "Urea",
      "BUN",
      "Lipid Profile*",
      "Fructosamine",
      "Urine for Ketones",
      "Comprehensive Urine Examination",
      "Microalbuminuria",
      "Creatinine",
      "Cystatin C",
    ],
    notes_contents: [
      "Tests marked with * require minimum 10-12 hours fasting.",
      "Tests marked with ** are to be performed as PP (post prandial i.e. 2 hours after finishing your meal).",
      "For tests related to diagnosing Type 1 Diabetes Mellitus, please ask our front office about the Type 1 Diabetes Autoimmune Antibody Panel.",
      "For tests related to resistant hypertension, such as Renin & Aldosterone, please ask our front office for further details.",
    ],
  },
  {
    id: 22,
    package_name: "Comprehensive Diabetes Profile",
    category: "Specialized",
    package_detail:
      "Comprehensive diabetes profile provides an edge over the tests in the diabetes and hypertension profile by giving an in-depth view of the function of kidneys and pancreas in relation to blood glucose levels. This profile is ideally suited for those who need to track diabetic markers holistically and require more detailed analysis. The additional tests in this profile include complete kidney function tests, fasting insulin, eGFR, HOMA-IR, and C-peptide.",
    package_rate: "7,500",
    tests_details: [
      "Blood Glucose Fasting*",
      "Blood Glucose PP**",
      "Fructosamine",
      "Urea",
      "Creatinine",
      "BUN",
      "Uric Acid",
      "Phosphorus",
      "Calcium",
      "Electrolytes (Na,K,Cl)",
      "Total Protein",
      "Albumin",
      "Albumin/Globulin ratio",
      "Urine for Ketones",
      "HbA1c (Glycosylated Hemoglobin)",
      "Comprehensive Urine Examination",
      "Microalbuminuria",
      "Lipid Profile*",
      "Insulin Fasting*",
      "Insulin PP**",
      "eGFR",
      "HOMA-IR* (Insulin Resistance Index)",
      "Cystatin C",
      "C-Peptide*",
    ],
    notes_contents: [
      "Tests marked with * require a minimum of 10-12 hours of fasting.",
      "Tests marked with ** are to be performed as PP (postprandial, i.e., 2 hours after finishing your meal).",
      "For tests related to diagnosing Type 1 Diabetes Mellitus, please ask our front office about the Diabetes Type 1 Autoimmune Antibody Panel.",
      "For tests related to resistant hypertension, such as Renin & Aldosterone, please ask our front office for further details.",
    ],
  },
  {
    id: 23,
    package_name: "Menopause Profile",
    category: "Specialized",
    package_detail:
      "At Dr. Dangs Lab, we recognise that menopause is a profound biological transition, influencing hormonal balance, metabolic health, and overall well-being. Our Menopause Profiles are meticulously curated to provide clinicians and patients with a comprehensive, evidence-based assessment of this life stage. These profiles serve as powerful tools for early intervention, personalised treatment planning, and optimising quality of life during midlife and beyond.",
    tests_details: [
      "Please refer to the detailed menopause profile options.",
    ],
    notes_contents: [],
  },
  {
    id: 24,
    package_name: "Bloating Profile",
    category: "Specialized",
    package_detail:
      "At Dr. Dangs Lab, we understand that bloating is more than just an inconvenience\u2014it can be a sign of underlying gastrointestinal, hormonal, or immune imbalances. Our Bloating Profiles are designed to pinpoint the cause through targeted, evidence-based testing, enabling precise diagnosis and personalised treatment strategies.",
    tests_details: ["Please refer to the detailed bloating profile options."],
    notes_contents: [
      {
        label: "Note",
        note: "Avoid antibiotics, bismuth-containing medications, and proton pump inhibitors (PPIs) for at least 10-14 days prior to the test. (Always consult your doctor before stopping any medications.)",
      },
    ],
  },
  {
    id: 25,
    package_name: "Longevity Panel",
    category: "Specialized",
    package_detail:
      "Dr. Dangs Lab presents the Longevity Profile - a sophisticated lens into biological aging and inflammation in the human body. By weaving together markers of inflammation, coagulation, cardiometabolic balance, immune vigilance, hormonal tone, vascular risk, and micronutrient sufficiency, this profile delivers a panoramic view of resilience, vitality, and long-term health potential. Establishing a baseline for these markers and monitoring them over time can be a valuable tool to track changes, guide interventions, and optimise long-term health outcomes.",
    package_rate: "35,000",
    tests_details: [
      "hs-CRP",
      "D-Dimer",
      "Fibrinogen",
      "Interleukin-6 (IL6)",
      "Extended lipid profile* (with Lipoprotien (a), Apolipoprotein A & B, Homocysteine)",
      "Anti TPO",
      "ANA (ELISA)",
      "Cortisol (AM)",
      "LpPLA2*",
      "MTHFR",
      "Vitamin C*",
      "Vitamin D",
      "HOMA-IR* (Insulin Resistance Index)",
      "Zinc",
      "Copper",
      "ZN / CU ratio",
    ],
    notes_contents: [
      "Tests marked with * require minimum 10-12 hours fasting.",
      "For details of TruAge Biological Age Test (TruAge measures key epigenetic and molecular markers to estimate your biological age, helping you understand how your body is aging compared to your chronological age and guiding personalised health and wellness strategies), kindly contact 999-999-2020 or our front desk. Or scan QR code to learn more about TruAge Biological Age Test.",
    ],
  },
  {
    id: 26,
    package_name: "Fatigue Profile",
    category: "Specialized",
    package_detail:
      "This profile helps in determining the causative factors of long-term fatigue and weakness. The profile includes an assessment of key vitamins, minerals and essential parameters, deficiency of which may cause fatigue. Additionally, it also includes an inflammatory marker, liver enzymes, electrolytes, blood counts along with a complete kidney function test, tests for diabetes, cortisol-the bodies stress hormone as well as urine analysis to ascertain the cause of fatigue. ANA (antinuclear antibody) screening for autoimmune disorders is also included in the fatigue profile.",
    package_rate: "12,700",
    tests_details: [
      "CBC",
      "Blood Glucose Random",
      "Kidney Function Test",
      "S.G.O.T",
      "S.G.P.T",
      "Sodium",
      "Potassium",
      "Chloride",
      "Magnesium",
      "Phosphorus",
      "HbA1c (Glycosylated Hemoglobin)",
      "Iron",
      "U.I.B.C.",
      "T.I.B.C.",
      "Transferrin Saturation",
      "Ferritin",
      "Thyroid Profile with FT3, FT4, Ultra-sensitive TSH",
      "Vitamin D3",
      "Microalbuminuria",
      "Comprehensive Urine Examination",
      "Cortisol (Morning)",
      "Active-B12 (Holotranscobalamin)",
      "Anti-Nuclear Antibody (Indirect Immunofluorescence)",
    ],
    notes_contents: [
      "For details of NEUROSPOT (a genetic test to assess vital parameters related to stress & fatigue including stress hormones & neurotransmitters) kindly contact 999-999-2020 or our frontdesk.",
    ],
  },
  {
    id: 27,
    package_name: "Basic Hairfall Profile",
    category: "Specialized",
    package_detail:
      "The Basic Hairfall Panel is designed to help identify common underlying causes of hair loss by assessing key health markers. Hairfall can result from a variety of factors, including hormonal imbalances, nutritional deficiencies, and other health issues. This comprehensive package includes essential tests such as the Thyroid profile with FT3, FT4, Ultra-sensitive TSH, CBC with ESR, Vitamins and Minerals Profile including levels of Magnesium, Vitamin D3, and Vitamin B12. It also measures Total Calcium, Phosphorus, Folic Acid (B9), Ferritin, Iron, TIBC, Transferrin Saturation, UIBC & Zinc. This profile also includes DHEAS (Dehydroepiandrosterone Sulfate) i.e. a hormone produced by the adrenal glands that serves as a precursor to male and female sex hormones. By evaluating these parameters, this panel assists in ruling out common causes and guiding appropriate treatment options.",
    package_rate: "9,500",
    tests_details: [
      "Thyroid Profile with FT3, FT4, Ultra-sensitive TSH",
      "CBC with ESR",
      "Vitamins & Minerals Profile (Vitamin D3, Total Calcium, Phosphorus, Vitamin B12, Vitamin B9/Folic Acid, Iron, Ferritin, U.I.B.C., T.I.B.C., Transferrin Saturation)",
      "Magnesium",
      "Zinc",
      "DHEAS (Dehydroepiandrosterone Sulfate)",
    ],
    notes_contents: [],
  },
  {
    id: 28,
    package_name: "Anemia Profile with HPLC",
    category: "Specialized",
    package_detail:
      "The Dr. Dangs Lab Anemia profile with HPLC not only diagnoses anemia but also helps ascertain the cause for the same. A complete blood count with reticulocyte count and detailed peripheral smear analysis provides a wealth of information in the assessment of a patient with anemia and guides whether these could be due to nutritional deficiency (Iron, Vitamin B12, Folate), abnormalities in red blood cells, abnormal Hemoglobins, infections, variant hemoglobinopathies, depressed marrow function or cancers. The work-up also includes evaluation to rule out autoimmune hemolytic anemia, with testing for Indirect Coombs Test (ICT), Direct Coombs Test (DCT), and serum haptoglobin.",
    package_rate: "7,800",
    tests_details: [
      "CBC with Reticulocytes",
      "LDH",
      "Iron",
      "Ferritin",
      "U.I.B.C.",
      "T.I.B.C.",
      "Transferrin Saturation",
      "Vitamin B12",
      "Folic Acid (Vitamin B9)",
      "HPLC",
      "Detailed Peripheral Smear Analysis",
      "STFR (Soluble Transferrin Receptor)",
      "Indirect Coombs Test (ICT)",
      "Direct Coombs Test",
      "Haptoglobin",
    ],
    notes_contents: [],
  },
  {
    id: 29,
    package_name: "Ultra Comprehensive Health Profile",
    category: "Comprehensive",
    package_detail:
      "This is an all-inclusive health check profile that provides detailed insights into the overall health status of an individual. In addition to the Comprehensive Health Profile (CHP), Ultra CHP1 includes HOMA-IR, a test assessing insulin resistance; Vitamins A, C, E & Urinary Iodine; serum protein electrophoresis; tests for evaluating levels of basic female hormones; cardiac assessment in the way of testing for high-sensitivity Troponin T & Lp-PLA2.",
    package_rate: "26,000",
    tests_details: [
      "CBC with ESR",
      "Blood Glucose Fasting*",
      "Blood Glucose PP**",
      "Lipid Profile*",
      "Kidney Function Test",
      "Liver Function Test",
      "Magnesium",
      "CPK",
      "Lipoprotein [a]",
      "Homocysteine",
      "Apolipoprotein A",
      "Apolipoprotein B",
      "Vitamins & Minerals Profile (Vitamin D3, Vitamin B12, Vitamin B9/Folic Acid, Iron, Ferritin, U.I.B.C., T.I.B.C., Transferrin Saturation, Zinc)",
      "Urinary Iodine*",
      "Copper",
      "ZN / CU ratio",
      "Thyroid Profile with FT3, FT4, Ultra-sensitive TSH",
      "HbA1c (Glycosylated Hemoglobin)",
      "Comprehensive Urine Examination",
      "IgE-Total",
      "hs-CRP",
      "Microalbuminuria",
      "Amylase",
      "Lipase",
      "Cystatin C",
      "HOMA-IR* (Insulin Resistance Index)",
      "hs Troponin T",
      "FSH",
      "LH",
      "Estrogen",
      "Vitamins A & E*",
      "Serum Protein electrophoresis",
      "Vitamin C*",
      "LpPLA2*",
    ],
    notes_contents: [
      "Tests marked with * require minimum 10-12 hours fasting.",
      "Tests marked with ** are to be performed as PP (post prandial i.e. 2 hours after finishing your meal)",
    ],
  },
  {
    id: 30,
    package_name: "Ultra Comprehensive Health Profile with PSA",
    category: "Comprehensive",
    package_detail:
      "This is an all inclusive health check profile that provides detailed insights on the overall health status of an individual. In addition to the Comprehensive Health Profile (CHP) with PSA, ultra CHP with PSA includes HOMA-IR; a test assessing insulin resistance, Vitamins A, C, E & Urinary Iodine, serum protein electrophoresis, tests for evaluating levels of basic hormones i.e. testosterone free & total, Cardiac assessment in the way of testing for high sensitivity Troponin T & Lp-PLA2. Also included is a urine test to check if your body has the iodine it needs for peak energy and metabolism.",
    package_rate: "27,500",
    tests_details: [
      "CBC with ESR",
      "Blood Glucose Fasting*",
      "Blood Glucose PP**",
      "Lipid Profile*",
      "Kidney Function Test",
      "Liver Function Test",
      "Magnesium",
      "CPK",
      "Lipoprotein [a]",
      "Homocysteine",
      "Apolipoprotein A",
      "Apolipoprotein B",
      "Vitamins & Minerals Profile (Vitamin D3, Vitamin B12, Vitamin B9/Folic Acid, Iron, Ferritin, U.I.B.C., T.I.B.C., Transferrin Saturation, Zinc)",
      "Copper",
      "ZN / CU ratio",
      "Thyroid Profile with FT3, FT4, Ultra-sensitive TSH",
      "HbA1c (Glycosylated Hemoglobin)",
      "Comprehensive Urine Examination",
      "IgE-Total",
      "hs-CRP",
      "Microalbuminuria",
      "Amylase",
      "Urinary Iodine*",
      "Lipase",
      "HOMA-IR* (Insulin Resistance Index)",
      "PSA-Total",
      "PSA Free",
      "hs Troponin T",
      "Testosterone Total",
      "Testosterone Free",
      "Estrogen (E2)",
      "Cystatin C",
      "Vitamins A & E*",
      "Serum Protein electrophoresis",
      "Vitamin C*",
      "LpPLA2*",
    ],
    notes_contents: [
      "Tests marked with * require minimum 10-12 hours fasting.",
      "Tests marked with ** are to be performed as PP (post prandial i.e. 2 hours after finishing your meal)",
    ],
  },
  {
    id: 31,
    package_name: "Fitness Profiles",
    category: "Specialized",
    package_detail:
      "The Dr. Dangs Lab Fitness Profile helps active individuals identify deficiencies affecting performance & issues like weakness, cramps, or electrolyte imbalance. It screens for anemia, diabetes, lipids, proteins, vitamins, minerals, kidney and muscle health. Separate Profiles are available for females and males. The male panel also includes Testosterone (free & total) and liver markers (SGOT, SGPT) for strength, muscle growth assessment and liver metabolism.",
    tests_details: ["Please refer to the detailed fitness profile options."],
    notes_contents: [
      {
        label: "Note",
        note: "Tests marked with * require minimum 10-12 hours fasting.",
      },
    ],
  },
];
